### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by jau88** [shinvou/Silentium#1]
Theos outputs errors on compiling; 
 theos "no visible @interface for 'psspecifier' declares the sector 'setIdentifier'

**Comment by shinvou** [comment]
Add this method to PSSpecifier.h in the Preferences framework: - (void)setIdentifier:(NSString *)identifier;

**Comment by jau88** [comment]
Thanks, works now. I also had to add these two methods afterwards (I am using rpetrich Headers).

PSListController.h
-(void)viewWillAppear:(BOOL)animated;

PSTableCell.h
- (id)initWithStyle:(int)style reuseIdentifier:(NSString *)identifier specifier:(PSSpecifier *)specifier;

**Comment by shinvou** [comment]
Great.
